### ISSUE TITLE
If you have issues with Bcrypt, this worked for me

### ISSUE THREAD

**Issue by bcmoore** [jonahroth/prospero#32]
In your gems folder

git clone https://github.com/codahale/bcrypt-ruby.git
cd bcrypt-ruby
gem build bcrypt.gemspec
gem install gem-compiler
gem compile bcrypt-3.1.10.gem
gem install bcrypt-3.1.10-x64-mingw32.gem --local

**Comment by jonahroth** [comment]
This would be great to add to the readme. Thanks Ben! :)
